import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/component/Providers";
import TopNav from "@/component/navbar/TopNav";
import React from "react";

export const metadata: Metadata = {
  title: "Conquest",
  description: "Generated by created next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
